Repository serverless/console, pull requests merged in 2022-04, with the labels that each got.

#24 Restrict eventData for only current requestId
  packages/aws-lambda-otel-extension/opt/otel-extension/internal/index.js
Labels: bug

#27 Initial documentation
  packages/aws-lambda-otel-extension-dist/README.md
  packages/aws-lambda-otel-extension/README.md
Labels: documentation

#41 Include req/res in README
  packages/aws-lambda-otel-extension/README.md
Labels: enhancement

#42 fix: update timeout message
  packages/aws-lambda-otel-extension/opt/otel-extension/internal/index.js
Labels: bug

#43 chore: Release v0.2.20
  packages/aws-lambda-otel-extension/CHANGELOG.md
  packages/aws-lambda-otel-extension/package.json
Labels: bug

#44 feat: Clean responses that are not JSON
  packages/aws-lambda-otel-extension/README.md
  packages/aws-lambda-otel-extension/opt/otel-extension/external/helper.js
  packages/aws-lambda-otel-extension/opt/otel-extension/external/index.js
  packages/aws-lambda-otel-extension/opt/otel-extension/package.json
  packages/aws-lambda-otel-extension/test/unit/external/helper.test.js
  packages/aws-lambda-otel-extension/test/unit/external/index.test.js
Labels: enhancement
