Repository serverless/console, pull requests merged in 2022-10, with the labels that each got.

#233 SDK Schema: Configure optional `request_body` and `response_body` tags
  proto/serverless/instrumentation/tags/v1/aws.proto
  proto/serverless/instrumentation/tags/v1/common.proto
Labels: enhancement

#232 SC-813: External extension with sdk endpoints
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/agent/http.go
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
  go/packages/dev-mode/lib/logger.go
  go/packages/dev-mode/main_test.go
  go/packages/dev-mode/utils/MockLambdAPI.go
  node/test/go/dev-mode/test/integration/index.test.js
Labels: enhancement

#238 chore: Updated sls tags to include additional identifying information
  proto/serverless/instrumentation/tags/v1/tags.proto
Labels: enhancement

#239 Created dev mode proto file
  proto/serverless/instrumentation/tags/v1/tags.proto
  proto/serverless/instrumentation/v1/dev_mode.proto
Labels: enhancement

#242 chore: Added name to buf.yml
  proto/buf.yaml
Labels: enhancement

#237 Forward all dev mode data as a application/x-protobuf
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/agent/http.go
  go/packages/dev-mode/lib/logger.go
  go/packages/dev-mode/main_test.go
  go/packages/dev-mode/utils/MockLambdAPI.go
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/go/dev-mode/test/lib/process-function.js
Labels: bug

#245 Converted payloads to dev mode paylods
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
  go/packages/dev-mode/lib/logger.go
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/go/dev-mode/test/lib/process-function.js
Labels: enhancement

#246 Release Dev Mode v0.2.0
  go/packages/dev-mode/version.txt
  node/test/go/dev-mode/test/integration/index.test.js
Labels: enhancement

#248 AWS Lambda SDK: Ensure opt-out for dev mode request and response monitoring
  node/packages/aws-lambda-sdk/.ts-types/instrument/index.d.ts
  node/packages/aws-lambda-sdk/README.md
  node/packages/aws-lambda-sdk/index.js
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v2.js
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v3-client.js
  node/packages/aws-lambda-sdk/lib/instrumentation/http.js
Labels: bug

#251 Added arm64 build and deploy
  .github/workflows/dev-mode-layer-publish.yml
  .github/workflows/dev-mode-validate.yml
  .github/workflows/node-integrate.yml
  go/packages/dev-mode/Makefile
Labels: enhancement

#252 chore: Release v0.2.1
  go/packages/dev-mode/version.txt
Labels: enhancement

#250 Optional telemetry data on dev mode proto
  go/packages/dev-mode/README.md
  proto/serverless/instrumentation/v1/dev_mode.proto
Labels: enhancement

#254 chore: Bump external port
  go/packages/dev-mode/agent/http.go
  go/packages/dev-mode/utils/MockLambdAPI.go
  go/packages/dev-mode/version.txt
Labels: enhancement

#256 chore: Release 0.3.1
  go/packages/dev-mode/version.txt
Labels: enhancement

#257 feat: Added multi-region endpoints
  go/packages/dev-mode/README.md
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/lib/publishUrl.go
Labels: enhancement

#258 chore: Release v0.3.2 region endpoints
  go/packages/dev-mode/version.txt
Labels: enhancement

#259 SC-861 Added telemetry data to dev mode payloads
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
  go/packages/dev-mode/lib/telemetryEnabledRegion.go
  go/packages/dev-mode/logsapi/client.go
  go/packages/dev-mode/main.go
Labels: enhancement

#260 chore: Release v0.3.3
  go/packages/dev-mode/version.txt
Labels: enhancement

#261 AWS Lambda SDK: Do not trace DynamoDb request `expressionValues`
  node/packages/aws-lambda-sdk/lib/instrumentation/aws-sdk/service-mapper.js
Labels: enhancement

#262 bug: Missing append logs
  go/packages/dev-mode/main.go
  go/packages/dev-mode/version.txt
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/go/dev-mode/test/lib/process-function.js
Labels: bug

#265 bug: Fixed missing traceId
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/main.go
  go/packages/dev-mode/version.txt
  node/test/go/dev-mode/test/integration/index.test.js
Labels: bug

#269 SDK Schema: Move span `input` and `output` data to top level properties
  proto/serverless/instrumentation/tags/v1/aws.proto
  proto/serverless/instrumentation/tags/v1/common.proto
  proto/serverless/instrumentation/v1/trace.proto
Labels: enhancement, breaking

#272 AWS Lambda SDK: Adapt `span.input` and `span.output`
  node/package.json
  node/packages/aws-lambda-sdk/.ts-types/index.d.ts
  node/packages/aws-lambda-sdk/.ts-types/lib/trace-span.d.ts
  node/packages/aws-lambda-sdk/docs/monitoring.md
  node/packages/aws-lambda-sdk/docs/trace-span.md
  node/packages/aws-lambda-sdk/instrument/lib/auto-send-spans.js
  node/packages/aws-lambda-sdk/instrument/lib/dev-mode-only-tags.js
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v2.js
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v3-client.js
  node/packages/aws-lambda-sdk/lib/instrumentation/http.js
  node/packages/aws-lambda-sdk/lib/trace-span/index.js
  node/packages/aws-lambda-sdk/package.json
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
  node/packages/aws-lambda-sdk/test/unit/lib/trace-span.test.js
Labels: enhancement, breaking

#274 chore: Release v0.12.0
  node/packages/sdk-schema/CHANGELOG.md
  node/packages/sdk-schema/package.json
  proto/README.md
Labels: enhancement

#275 Update external
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
  go/packages/dev-mode/main_test.go
  go/packages/dev-mode/version.txt
  node/test/go/dev-mode/test/integration/index.test.js
Labels: enhancement

#277 chore: Bump s3 dependency
  go/packages/dev-mode/version.txt
  node/package.json
  node/packages/aws-lambda-sdk/CHANGELOG.md
  node/packages/aws-lambda-sdk/package.json
Labels: bug

#278 bug: Fixed traceId processing
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/main.go
  go/packages/dev-mode/version.txt
Labels: bug

#279 SC-902 Removed severity calculation
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/version.txt
Labels: bug

#280 feat: Added timestamp to req/res payloads
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/package.json
Labels: enhancement

#281 bug: Matched invocation start/end time
  node/packages/aws-lambda-sdk/CHANGELOG.md
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/lib/trace-span/index.js
  node/packages/aws-lambda-sdk/package.json
Labels: bug

#285 AWS Lambda SDK: Fix capture of HTTP response body when it's a string
  node/packages/aws-lambda-sdk/lib/instrumentation/http.js
Labels: bug

#286 SDK Schema: In `requestResponse` payload, replace `data` with `body` and `origin`
  node/packages/sdk-schema/test/unit/requestResponse.test.js
  proto/serverless/instrumentation/v1/request_response.proto
Labels: enhancement, breaking

#288 SDK Schema: Support Node.js v12
  node/packages/sdk-schema/tsconfig.rollup.json
Labels: enhancement

#291 Updated req/res schema
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
  go/packages/dev-mode/version.txt
Labels: enhancement

#293 Fix release for go extension
  go/packages/dev-mode/version.txt
  node/test/go/dev-mode/test/integration/index.test.js
Labels: bug

#294 AWS Lambda SDK: Fix handling of `undefined` lambda responses
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/callback-no-result.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: bug
