Repository serverless/console, pull requests merged in 2022-09, with the labels that each got.

#170 AWS Lambda SDK: Instrument API Gateway HTTP API (v1 payload) events
  node/package.json
  node/packages/aws-lambda-sdk/docs/sdk-trace.md
  node/packages/aws-lambda-sdk/lib/resolve-event-tags.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/lib/cleanup.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: enhancement

#171 AWS Lambda SDK: Instrument API Gateway HTTP API (v2 payload) events
  node/packages/aws-lambda-sdk/docs/sdk-trace.md
  node/packages/aws-lambda-sdk/lib/resolve-event-tags.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: enhancement

#172 SDK Schema: Remove tags that not apply `aws.lambda` span
  proto/serverless/instrumentation/tags/v1/aws.proto
Labels: bug, breaking

#174 AWS Lambda SDK: Instrument SNS events
  node/package.json
  node/packages/aws-lambda-sdk/docs/sdk-trace.md
  node/packages/aws-lambda-sdk/lib/resolve-event-tags.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/lib/cleanup.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: enhancement

#186 AWS Lambda SDK: Fix wrapping of nested ESM handlers
  node/packages/aws-lambda-sdk/internal-extension/index.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/esm-nested/.eslintrc.cjs
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/esm-nested/nested/within/index.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/esm-nested/package.json
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/lib/resolve-test-variants-config.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: bug

#191 chore: Updated proto docs
  proto/serverless/instrumentation/tags/v1/aws.proto
  proto/serverless/instrumentation/tags/v1/tags.proto
  proto/serverless/instrumentation/v1/trace.proto
Labels: enhancement

#194 SDK Schema: Cleanup base properties of AWS SDK spans
  proto/serverless/instrumentation/tags/v1/aws.proto
Labels: enhancement

#203 SDK Schema: Improve types of numeric properties
  node/packages/sdk-schema/test/unit/span.test.js
  proto/serverless/instrumentation/tags/v1/aws.proto
  proto/serverless/instrumentation/tags/v1/common.proto
Labels: enhancement, breaking

#210 SDK Schema: Improve `outcome` documentation
  proto/serverless/instrumentation/tags/v1/aws.proto
Labels: documentation

#208 SDK Schema: Define `exclusive_start_key` and `attribute_values` DynamoDB tags
  proto/serverless/instrumentation/tags/v1/aws.proto
Labels: enhancement

#209 AWS Lambda SDK: Support new AWS SDK DynamoDB tags
  node/packages/aws-lambda-sdk/lib/instrument/aws-sdk/service-mapper.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
Labels: enhancement

#188 Dev Mode Extension
  .github/workflows/dev-mode-layer-publish.yml
  .github/workflows/dev-mode-validate.yml
  .github/workflows/node-integrate.yml
  go/packages/dev-mode/.gitignore
  go/packages/dev-mode/Makefile
  go/packages/dev-mode/README.md
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/agent/http.go
  go/packages/dev-mode/extension/client.go
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
  go/packages/dev-mode/lib/logger.go
  go/packages/dev-mode/logsapi/client.go
  go/packages/dev-mode/main.go
  go/packages/dev-mode/main_test.go
  go/packages/dev-mode/utils/MockLambdAPI.go
  go/packages/dev-mode/version.txt
  node/.eslintrc.js
  node/package.json
  node/test/go/dev-mode/README.md
  node/test/go/dev-mode/test/fixtures/lambdas/.eslintrc.js
  node/test/go/dev-mode/test/fixtures/lambdas/4s-logger.js
  node/test/go/dev-mode/test/fixtures/lambdas/package.json
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/go/dev-mode/test/lib/basename.js
  node/test/go/dev-mode/test/lib/cleanup.js
  node/test/go/dev-mode/test/lib/create-core-resources.js
  node/test/go/dev-mode/test/lib/process-function.js
  node/test/go/dev-mode/test/lib/resolve-test-variants-config.js
  node/test/go/dev-mode/test/lib/test-uid.js
  node/test/go/dev-mode/test/utils/aws-request.js
  node/test/go/dev-mode/test/utils/resolve-dir-zip-buffer.js
Labels: enhancement

#217 Fixed layer publish workflow
  .github/workflows/dev-mode-layer-publish.yml
Labels: bug

#218 Bump go extension version
  .github/workflows/dev-mode-layer-publish.yml
  go/packages/dev-mode/version.txt
Labels: bug

#219 Added go path to integrate
  .github/workflows/node-integrate.yml
  go/packages/dev-mode/version.txt
Labels: bug

#220 bug: Fixed extension path
  .github/workflows/dev-mode-layer-publish.yml
  go/packages/dev-mode/version.txt
Labels: bug

#221 Upgrade dev mode processing endpoint
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
  go/packages/dev-mode/main.go
  go/packages/dev-mode/main_test.go
  go/packages/dev-mode/utils/MockLambdAPI.go
  go/packages/dev-mode/version.txt
  node/package.json
  node/test/go/dev-mode/test/fixtures/lambdas/4s-logger.js
  node/test/go/dev-mode/test/integration/index.test.js
Labels: enhancement

#222 SDK Schema: Remove `express` tags in favor of `aws.lambda.http_router`
  proto/serverless/instrumentation/tags/v1/aws.proto
  proto/serverless/instrumentation/tags/v1/nodejs.proto
  proto/serverless/instrumentation/tags/v1/tags.proto
Labels: enhancement, breaking

#225 feat: Add support for API tokens
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/lib/logger.go
  go/packages/dev-mode/logsapi/client.go
  go/packages/dev-mode/main.go
  go/packages/dev-mode/version.txt
Labels: enhancement

#227 Added org token header
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/lib/logger.go
  go/packages/dev-mode/version.txt
Labels: enhancement

#226 AWS Lambda SDK: Function URL events support
  node/packages/aws-lambda-sdk/docs/sdk-trace.md
  node/packages/aws-lambda-sdk/instrument/lib/resolve-event-tags.js
  node/packages/aws-lambda-sdk/instrument/lib/resolve-response-tags.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: enhancement

#228 feat: Added req/res forwarding
  .github/workflows/node-integrate.yml
  go/packages/dev-mode/Makefile
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/lib/logger.go
  go/packages/dev-mode/main_test.go
  go/packages/dev-mode/utils/MockLambdAPI.go
  go/packages/dev-mode/version.txt
  node/test/go/dev-mode/README.md
  node/test/go/dev-mode/test/fixtures/lambdas/with-internal.js
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/go/dev-mode/test/lib/create-core-resources.js
  node/test/go/dev-mode/test/lib/process-function.js
Labels: enhancement

#231 bug: Fixed reqres region
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/version.txt
  node/test/go/dev-mode/test/integration/index.test.js
Labels: bug
