Repository serverless/console, pull requests merged in 2023-01, with the labels that each got.

#332 AWS Lambda SDK: Report captured events with a trace
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/sdk.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: enhancement

#341 SC-148 Added started/ended events for non SDK functions
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/main_test.go
Labels: enhancement

#338 SDK: Instrument `console.error`
  node/packages/sdk/.ts-types/index.d.ts
  node/packages/sdk/README.md
  node/packages/sdk/docs/instrumentation/node-console.md
  node/packages/sdk/index.js
  node/packages/sdk/lib/instrumentation/node-console.js
Labels: enhancement

#344 SC-152 Updated initialization error handling
  go/packages/dev-mode/main.go
  go/packages/dev-mode/main_test.go
Labels: bug

#345 AWS Lambda SDK: Initialize original handler at AWS intended processing point
  node/packages/aws-lambda-sdk/internal-extension/index.js
  node/packages/aws-lambda-sdk/internal-extension/wrapper.js
  node/packages/aws-lambda-sdk/scripts/lib/build.js
Labels: bug

#346 SDK: Instrument `console.warn`
  node/packages/sdk/index.js
  node/packages/sdk/lib/instrumentation/node-console.js
Labels: enhancement

#352 Bumped proto version
  go/packages/dev-mode/go.mod
  go/packages/dev-mode/go.sum
Labels: enhancement

#351 Release v0.5.4
  go/packages/dev-mode/version.txt
Labels: bug

#354 fix: Added v3 document client support
  node/packages/aws-lambda-sdk/lib/instrumentation/aws-sdk/service-mapper.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/aws-sdk-v2.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/aws-sdk-v3.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/package.json
  node/packages/aws-lambda-sdk/test/integration/index.test.js
Labels: bug

#353 fix: Added _origin to captured event before emit
  node/packages/sdk/lib/captured-event.js
  node/packages/sdk/lib/create-error-captured-event.js
  node/packages/sdk/lib/create-warning-captured-event.js
  node/packages/sdk/lib/instrumentation/node-console.js
Labels: bug

#361 chore: Release v0.2.3
  node/packages/sdk/CHANGELOG.md
  node/packages/sdk/package.json
Labels: bug

#363 SDK: Support custom fingeprints
  node/packages/sdk/.ts-types/index.d.ts
  node/packages/sdk/docs/sdk.md
  node/packages/sdk/lib/captured-event.js
  node/packages/sdk/lib/create-error-captured-event.js
  node/packages/sdk/lib/create-warning-captured-event.js
  node/packages/sdk/test/unit/lib/captured-event.test.js
  node/packages/sdk/test/unit/lib/create-error-captured-event.test.js
  node/packages/sdk/test/unit/lib/create-warning-captured-event.test.js
Labels: enhancement

#342 SDK: SC-256 Initial Python SDK, CI, tests
  .github/workflows/python-validate.yml
  proto/buf.gen.yaml
  python/packages/sdk-schema/.gitignore
  python/packages/sdk-schema/pyproject.toml
  python/packages/sdk/pyproject.toml
  python/packages/sdk/sdk/__init__.py
  python/packages/sdk/sdk/py.typed
  python/packages/sdk/sdk/tests/__init__.py
  python/packages/sdk/sdk/tests/test_sdk.py
  python/packages/sdk/setup.cfg
  python/packages/sdk/setup.py
Labels: enhancement

#355 SDK: SC-257 `TraceSpan` implementation, unit tests
  .github/workflows/python-validate.yml
  python/packages/sdk/pyproject.toml
  python/packages/sdk/sdk/__init__.py
  python/packages/sdk/sdk/base.py
  python/packages/sdk/sdk/exceptions.py
  python/packages/sdk/sdk/sdk/__init__.py
  python/packages/sdk/sdk/sdk/base.py
  python/packages/sdk/sdk/span/__init__.py
  python/packages/sdk/sdk/span/id.py
  python/packages/sdk/sdk/span/name.py
  python/packages/sdk/sdk/span/tags.py
  python/packages/sdk/sdk/span/trace.py
  python/packages/sdk/sdk/tests/__init__.py
  python/packages/sdk/sdk/tests/test_id.py
  python/packages/sdk/sdk/tests/test_name.py
  python/packages/sdk/sdk/tests/test_sdk.py
  python/packages/sdk/sdk/tests/test_tags.py
  python/packages/sdk/sdk/tests/test_trace_span.py
  python/packages/sdk/setup.py
Labels: enhancement

#362 Schema: `WarningTags.type` to distinguish between internal and user generated warnings
  proto/serverless/instrumentation/tags/v1/warning.proto
Labels: enhancement

#368 AWS Lambda SDK: Revert problamatic TS addition
  node/packages/sdk/.ts-types/index.d.ts
  node/packages/sdk/index.ts
Labels: bug

#369 fix: Fixed typings file
  node/packages/sdk/.ts-types/index.d.ts
Labels: bug

#371 chore: Improved types
  node/packages/sdk/.ts-types/index.d.ts
Labels: enhancement

#374 SDK: Make `createTraceSpan` private
  node/packages/sdk/.ts-types/index.d.ts
  node/packages/sdk/.ts-types/lib/trace-span.d.ts
  node/packages/sdk/README.md
  node/packages/sdk/docs/sdk.md
  node/packages/sdk/docs/trace-span.md
  node/packages/sdk/index.js
  node/packages/sdk/lib/instrumentation/express/instrument-layer-prototype.js
  node/packages/sdk/lib/instrumentation/http.js
Labels: enhancement, breaking, runtime/node.js

#375 SDK: Dedicated handling for structured warnings issued by the SDK
  node/packages/sdk/lib/create-warning-captured-event.js
  node/packages/sdk/lib/instrumentation/node-console.js
  node/packages/sdk/test/unit/lib/create-warning-captured-event.test.js
  node/packages/sdk/test/unit/lib/instrumentation/node-console.test.js
Labels: enhancement, runtime/node.js

#373 AWS Lambda SDK: Test: Fix tests that confirm on dynamodb document client
  node/packages/aws-lambda-sdk/test/integration/index.test.js
Labels: runtime/node.js, tests

#378 AWS Lambda SDK: Report internal warnings with structured logs
  node/packages/aws-lambda-sdk/.eslintrc.js
  node/packages/aws-lambda-sdk/instrument/lib/send-telemetry.js
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v2.js
  node/packages/aws-lambda-sdk/trace-spans/aws-lambda.js
Labels: enhancement, runtime/node.js

#380 feat: Added increasing string as sequenceId
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/main_test.go
Labels: enhancement

#383 SDK: Define `Span.custom_tags` to host custom user tags
  proto/serverless/instrumentation/v1/trace.proto
Labels: enhancement, runtime/node.js

#381 chore: Release v0.5.5
  go/packages/dev-mode/version.txt
Labels: enhancement

#384 SDK: `serverless.setTag` implementation
  node/package.json
  node/packages/sdk/.ts-types/index.d.ts
  node/packages/sdk/docs/sdk.md
  node/packages/sdk/index.js
  node/packages/sdk/lib/trace-span.js
  node/packages/sdk/test/unit/index.test.js
  node/packages/sdk/test/unit/lib/trace-span.test.js
Labels: enhancement, runtime/node.js

#388 AWS Lambda SDK: Upgrade to `@serverless/sdk` v0.3.1
  node/packages/aws-lambda-sdk/index.js
  node/packages/aws-lambda-sdk/package.json
Labels: runtime/node.js, refactor

#356 SDK: SC-258 Protobuf generation & interfaces, unit tests, CI
  .github/workflows/python-validate.yml
  proto/buf.gen.python.yaml
  proto/buf.gen.yaml
  python/packages/sdk-schema/.gitignore
  python/packages/sdk-schema/pyproject.toml
  python/packages/sdk-schema/scripts/build.sh
  python/packages/sdk-schema/scripts/install.sh
  python/packages/sdk-schema/sdk_schema/__init__.py
  python/packages/sdk-schema/sdk_schema/tests/__init__.py
  python/packages/sdk-schema/sdk_schema/tests/test_schema.py
Labels: enhancement, runtime/python

#390 AWS Lambda SDK: Handle gently non JSON compliant AWS SDK input and output
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v2.js
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v3-client.js
  node/packages/aws-lambda-sdk/lib/instrumentation/aws-sdk/safe-stringify.js
Labels: bug, runtime/node.js

#393 AWS Lambda SDK: Ensure to not instrument S3 requests signing
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v2.js
  node/packages/aws-lambda-sdk/instrumentation/aws-sdk-v3-client.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/aws-sdk-v2.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/aws-sdk-v3.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/package.json
Labels: bug, runtime/node.js

#395 SDK: Ensure not to crash on invalid `serverless.setTag` input
  node/packages/sdk/index.js
  node/packages/sdk/test/unit/index.test.js
Labels: bug, runtime/node.js

#396 AWS Lambda SDK: Propagate all captured events to `dev mode`
  node/packages/aws-lambda-sdk/instrument/lib/auto-send-spans.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: enhancement, runtime/node.js

#397 Schema: Define `TracePayload.custom_tags`
  proto/serverless/instrumentation/v1/trace.proto
Labels: enhancement

#365 SDK: SC-259 Publication of new versions
  .github/workflows/python-integrate.yaml
  .github/workflows/python-sdk-publish.yaml
  .github/workflows/python-sdk-schema-publish.yaml
  proto/buf.gen.python.yaml
  python/packages/sdk-schema/.gitignore
  python/packages/sdk-schema/scripts/build.sh
  python/packages/sdk-schema/serverless_sdk_schema/__init__.py
  python/packages/sdk-schema/serverless_sdk_schema/tests/__init__.py
  python/packages/sdk-schema/serverless_sdk_schema/tests/test_schema.py
  python/packages/sdk/serverless_sdk/__init__.py
  python/packages/sdk/serverless_sdk/base.py
  python/packages/sdk/serverless_sdk/exceptions.py
  python/packages/sdk/serverless_sdk/py.typed
  python/packages/sdk/serverless_sdk/sdk/__init__.py
  python/packages/sdk/serverless_sdk/sdk/base.py
  python/packages/sdk/serverless_sdk/span/__init__.py
  python/packages/sdk/serverless_sdk/span/id.py
  python/packages/sdk/serverless_sdk/span/name.py
  python/packages/sdk/serverless_sdk/span/tags.py
  python/packages/sdk/serverless_sdk/span/trace.py
  python/packages/sdk/serverless_sdk/tests/__init__.py
  python/packages/sdk/serverless_sdk/tests/test_id.py
  python/packages/sdk/serverless_sdk/tests/test_name.py
  python/packages/sdk/serverless_sdk/tests/test_sdk.py
  python/packages/sdk/serverless_sdk/tests/test_tags.py
  python/packages/sdk/serverless_sdk/tests/test_trace_span.py
Labels: runtime/python, ci

#401 feat: Serialize `TraceSpan` neatly
  python/packages/sdk/pyproject.toml
  python/packages/sdk/serverless_sdk/span/trace.py
Labels: bug, runtime/python

#403 SDK: Store global tags on SDK directly, not on root span
  node/packages/sdk/docs/sdk.md
  node/packages/sdk/index.js
  node/packages/sdk/test/unit/index.test.js
Labels: bug, breaking, runtime/node.js, refactor

#407 SDK: Release v0.4.0
  node/packages/sdk/CHANGELOG.md
  node/packages/sdk/package.json
Labels: runtime/node.js

#408 AWS Lambda SDK: Expose custom tags directly on trace instead of root span
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/instrument/lib/auto-send-spans.js
  node/packages/aws-lambda-sdk/package.json
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: breaking, runtime/node.js, refactor

#409 AWS Lambda SDK: Report outcome error data with event instead of root span tags
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: breaking, runtime/node.js, refactor

#398 fix: Log console messages as events
  go/packages/dev-mode/agent/forwarder.go
  node/package.json
  node/test/go/dev-mode/test/fixtures/lambdas/with-internal.js
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/go/dev-mode/test/lib/process-function.js
Labels: bug

#411 chore: Release v0.5.6 of dev mode
  go/packages/dev-mode/version.txt
Labels: bug

#413 AWS Lambda SDK: Ensure to clear custom tags collection between invocations
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/sdk.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: bug, runtime/node.js

#416 Schema: Define `WarningTags.stacktrace`
  proto/serverless/instrumentation/tags/v1/warning.proto
Labels: enhancement

#417 Test: Collect any printed protobuf payload
  node/test/lib/get-process-function.js
Labels: runtime/node.js, tests

#415 chore: Updated dev mode integration tests
  go/packages/dev-mode/lib/logger.go
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/go/dev-mode/test/lib/basename.js
  node/test/go/dev-mode/test/lib/cleanup.js
  node/test/go/dev-mode/test/lib/create-core-resources.js
  node/test/go/dev-mode/test/lib/process-function.js
  node/test/go/dev-mode/test/lib/resolve-test-variants-config.js
  node/test/go/dev-mode/test/lib/test-uid.js
  node/test/go/dev-mode/test/utils/aws-request.js
  node/test/go/dev-mode/test/utils/resolve-dir-zip-buffer.js
  node/test/lib/cleanup.js
  node/test/lib/get-process-function.js
Labels: enhancement

#419 SDK: Store stacktrace with each captured event
  node/packages/sdk/lib/create-error-captured-event.js
  node/packages/sdk/lib/create-warning-captured-event.js
  node/packages/sdk/lib/resolve-stack-trace-string.js
  node/packages/sdk/test/unit/lib/create-error-captured-event.test.js
  node/packages/sdk/test/unit/lib/create-warning-captured-event.test.js
  node/packages/sdk/test/utils/normalize-captured-event-tags.js
Labels: enhancement, runtime/node.js

#420 SDK: Cover each `console.error` invocation with captured event
  node/packages/sdk/lib/instrumentation/node-console.js
  node/packages/sdk/test/unit/lib/instrumentation/node-console.test.js
Labels: enhancement, runtime/node.js

#423 AWS Lambda SDK: Upgrade to SDK v0.4.1
  node/packages/aws-lambda-sdk/package.json
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/sdk.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
  node/packages/aws-lambda-sdk/test/unit/internal-extension/index.test.js
Labels: runtime/node.js, refactor

#426 SDK: Fix manual express instrumentation
  node/package.json
  node/packages/sdk/instrumentation/express-app.js
  node/packages/sdk/test/unit/instrumentation/express-app.test.js
  node/packages/sdk/test/unit/lib/instrumentation/node-console.test.js
Labels: bug, runtime/node.js

#430 AWS Lambda SDK: Fix invocation closure race condition
  node/packages/aws-lambda-sdk/instrument/index.js
  node/packages/aws-lambda-sdk/test/fixtures/lambdas/error-uncaught-resolution-race.js
  node/packages/aws-lambda-sdk/test/integration/index.test.js
Labels: bug, runtime/node.js

#432 feat: Updated timeout reponse to include an error tag
  go/packages/dev-mode/agent/forwarder.go
  go/packages/dev-mode/lib/telemetryEnabledRegion.go
  go/packages/dev-mode/logsapi/client.go
  go/packages/dev-mode/utils/MockLambdAPI.go
  node/test/go/dev-mode/test/fixtures/lambdas/timeout.js
  node/test/go/dev-mode/test/integration/index.test.js
  node/test/lib/get-process-function.js
Labels: bug

#434 chore: Release v0.5.7
  go/packages/dev-mode/version.txt
Labels: bug

#437 fix: Fixed traceId on generated responses
  go/packages/dev-mode/agent/forwarder.go
  node/test/go/dev-mode/test/fixtures/lambdas/timeout-with-internal.js
  node/test/go/dev-mode/test/integration/index.test.js
Labels: bug

#438 chore: Release v0.5.8
  go/packages/dev-mode/version.txt
Labels: bug
